Added send message to a channel functionality
daveRanjan/stomper pull request #15
Opened 2021-10-07 11:54 UTC by daveRanjan

2021-10-07 11:58 UTC, monis01 requested changes
Please check comment

2021-10-07 11:58 UTC, monis01 commented on src/app/app.component.ts
> +    this.socketService?.send(this.messageChannelName, this.message)
Is there any chance that stockService will not be available when we will be calling `onSend` ?? so do we require 
this.socketService'?'.send..... ???

2021-10-08 07:28 UTC, daveRanjan commented on src/app/app.component.ts
> +    this.socketService?.send(this.messageChannelName, this.message)
If the user tries to send message before connecting it will break

2021-10-08 07:40 UTC, monis01 commented on src/app/app.component.ts
> +    this.socketService?.send(this.messageChannelName, this.message)
But the initiation of sending ba message is by clicking on button.
Once we click on button, event will triggered and at that point service will be initiated.
Or am I missing any context here?

2021-10-08 07:48 UTC, merged

2021-10-08 07:49 UTC, daveRanjan commented on src/app/app.component.ts
> +    this.socketService?.send(this.messageChannelName, this.message)
but the user can choose to click on send button even without connecting
though this should be added as validation check. but for now this is fine.